import {
    StyleSheet
} from 'react-native';

const styles = StyleSheet.create({
    box:{
        backgroundColor:'white',
        width:'80%',
        height:630,
        padding:20,
    },
    position_box:{
        alignItems:'center',
        justifyContent:'center',
        paddingTop:'16%',
    },
    position_box2:{
        alignItems:'center',
        justifyContent:'center',
        paddingTop:20,
        paddingBottom:15,
    },
    text2:{
        color:'black',
    },
    text3:{
        color:'#cd5c5c',
        fontWeight:'bold',
        fontSize:20,
    },
    text4:{
        color:'#cd5c5c',
        fontWeight:'bold',
        fontSize:20,
        paddingBottom:5,
    },
    total :{
        flexDirection:'row',
        paddingTop:15,
    },
    boxDetail:{
        backgroundColor:'#e8e8e8',
        width:'100%',
        height:230,
        padding:20,
    },
    harbor:{
        flexDirection:'row',
        paddingBottom:10,
    },
    origin:{
        flex:1,
        fontWeight:'bold',
        fontSize:17,
        color:'black',
    },
    destination:{
        fontWeight:'bold',
        fontSize:17,
        color:'black',
    },
    title:{
        color:'#cd5c5c',
        fontWeight:'bold',
    },
    title2:{
        paddingTop:10,
        fontWeight:'bold',
        color:'black',
    },
    text:{
        color:'black',
        fontWeight:'bold',
        padding:10,
        paddingLeft:5,
    },
    border:{
        borderBottomColor: 'black',
        borderBottomWidth: 1,
        paddingTop:10,
    },
    price:{
        paddingTop:15,
        textAlign:'right',
        color:'black',
        fontWeight:'bold',
    },
    position_btn:{
        alignItems:'center',
        justifyContent:'center',
        paddingTop:'16%',
        flexDirection:'row',
    },
    btn_detail:{
        width:'40%',
    },
    TextInput:{
        borderWidth:1,
        width:'100%',
        borderRadius:10,
        color:'black',
        padding:5,
        paddingLeft:10,
    },
});
export default styles;